export const TASK_ACTION_SUCCESS = 'TASK_ACTION_SUCCESS';
export const FETCH_USER_TASKS_SUCCESS = 'FETCH_USER_TASKS_COMPLETE';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const CREATION_TASK_SUCCESS = 'CREATION_TASK_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';